# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: root

    steps:
    - uses: actions/checkout@v3

    - name: "Mysql Setup"
      run : |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          go.sum
          go.mod
          bin/
          pkg/
          src/
